In [1]:
import numpy as np
import math
l = float(input("Length of the surface:"))
d = float(input("Depth of the surface:"))
w = float(input("Width of the hole:"))
dh = float(input("Diameter of the hole:"))
db = float(input("Diameter of the bigger spheres:"))
ds = float(input("Diameter of the smaller spheres:"))
num = int(input("Number of atoms in the polymer chain:"))

Length of the surface:100
Depth of the surface:40
Width of the hole:40
Diameter of the hole:10
Diameter of the bigger spheres:1
Diameter of the smaller spheres:1


In [2]:
 a = math.acos((((2*(dh**2))-((ds**2)))/(2*(dh**2))))

In [3]:
print(a)

0.10004171361154007


In [4]:
Z = []
t=-w/2
while(t<=w/2):
    Z.append(t)
    t=t+ds

In [5]:
print(Z)

[-20.0, -19.0, -18.0, -17.0, -16.0, -15.0, -14.0, -13.0, -12.0, -11.0, -10.0, -9.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0]


In [6]:
angle=0
ans=([])
temp=[]
while(angle+a<2*math.pi):
    x=(dh/2)*(math.cos(angle))
    y=(dh/2)*(math.sin(angle))
    temp.append(np.array([x,y]))
    for z in Z:
        print(z)
        ans.append(([1,x,y,z]))
    angle=angle+a

-20.0
-19.0
-18.0
-17.0
-16.0
-15.0
-14.0
-13.0
-12.0
-11.0
-10.0
-9.0
-8.0
-7.0
-6.0
-5.0
-4.0
-3.0
-2.0
-1.0
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
-20.0
-19.0
-18.0
-17.0
-16.0
-15.0
-14.0
-13.0
-12.0
-11.0
-10.0
-9.0
-8.0
-7.0
-6.0
-5.0
-4.0
-3.0
-2.0
-1.0
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
-20.0
-19.0
-18.0
-17.0
-16.0
-15.0
-14.0
-13.0
-12.0
-11.0
-10.0
-9.0
-8.0
-7.0
-6.0
-5.0
-4.0
-3.0
-2.0
-1.0
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
-20.0
-19.0
-18.0
-17.0
-16.0
-15.0
-14.0
-13.0
-12.0
-11.0
-10.0
-9.0
-8.0
-7.0
-6.0
-5.0
-4.0
-3.0
-2.0
-1.0
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
-20.0
-19.0
-18.0
-17.0
-16.0
-15.0
-14.0
-13.0
-12.0
-11.0
-10.0
-9.0
-8.0
-7.0
-6.0
-5.0
-4.0
-3.0
-2.0
-1.0
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0


In [7]:
print(ans)

[[1, 5.0, 0.0, -20.0], [1, 5.0, 0.0, -19.0], [1, 5.0, 0.0, -18.0], [1, 5.0, 0.0, -17.0], [1, 5.0, 0.0, -16.0], [1, 5.0, 0.0, -15.0], [1, 5.0, 0.0, -14.0], [1, 5.0, 0.0, -13.0], [1, 5.0, 0.0, -12.0], [1, 5.0, 0.0, -11.0], [1, 5.0, 0.0, -10.0], [1, 5.0, 0.0, -9.0], [1, 5.0, 0.0, -8.0], [1, 5.0, 0.0, -7.0], [1, 5.0, 0.0, -6.0], [1, 5.0, 0.0, -5.0], [1, 5.0, 0.0, -4.0], [1, 5.0, 0.0, -3.0], [1, 5.0, 0.0, -2.0], [1, 5.0, 0.0, -1.0], [1, 5.0, 0.0, 0.0], [1, 5.0, 0.0, 1.0], [1, 5.0, 0.0, 2.0], [1, 5.0, 0.0, 3.0], [1, 5.0, 0.0, 4.0], [1, 5.0, 0.0, 5.0], [1, 5.0, 0.0, 6.0], [1, 5.0, 0.0, 7.0], [1, 5.0, 0.0, 8.0], [1, 5.0, 0.0, 9.0], [1, 5.0, 0.0, 10.0], [1, 5.0, 0.0, 11.0], [1, 5.0, 0.0, 12.0], [1, 5.0, 0.0, 13.0], [1, 5.0, 0.0, 14.0], [1, 5.0, 0.0, 15.0], [1, 5.0, 0.0, 16.0], [1, 5.0, 0.0, 17.0], [1, 5.0, 0.0, 18.0], [1, 5.0, 0.0, 19.0], [1, 5.0, 0.0, 20.0], [1, 4.975, 0.4993746088859547, -20.0], [1, 4.975, 0.4993746088859547, -19.0], [1, 4.975, 0.4993746088859547, -18.0], [1, 4.975, 0.4993746

In [8]:
import matplotlib.pyplot as plt
%matplotlib inline


In [9]:
dis = ds/2 + db/2
X = []
Y = []
tx = -l/2
ty = -d/2
while(tx<=l/2):
    X.append(tx)
    tx=tx+db
while(ty<=d/2):
    Y.append(ty)
    ty=ty+db

In [10]:
for x in X:
    for y in Y:
        if((x**2)+(y**2)>(dh/2+dis)**2):
            ans.append([1,x,y,-w/2])
            ans.append([1,x,y,w/2])

In [11]:
print(ans)

[[1, 5.0, 0.0, -20.0], [1, 5.0, 0.0, -19.0], [1, 5.0, 0.0, -18.0], [1, 5.0, 0.0, -17.0], [1, 5.0, 0.0, -16.0], [1, 5.0, 0.0, -15.0], [1, 5.0, 0.0, -14.0], [1, 5.0, 0.0, -13.0], [1, 5.0, 0.0, -12.0], [1, 5.0, 0.0, -11.0], [1, 5.0, 0.0, -10.0], [1, 5.0, 0.0, -9.0], [1, 5.0, 0.0, -8.0], [1, 5.0, 0.0, -7.0], [1, 5.0, 0.0, -6.0], [1, 5.0, 0.0, -5.0], [1, 5.0, 0.0, -4.0], [1, 5.0, 0.0, -3.0], [1, 5.0, 0.0, -2.0], [1, 5.0, 0.0, -1.0], [1, 5.0, 0.0, 0.0], [1, 5.0, 0.0, 1.0], [1, 5.0, 0.0, 2.0], [1, 5.0, 0.0, 3.0], [1, 5.0, 0.0, 4.0], [1, 5.0, 0.0, 5.0], [1, 5.0, 0.0, 6.0], [1, 5.0, 0.0, 7.0], [1, 5.0, 0.0, 8.0], [1, 5.0, 0.0, 9.0], [1, 5.0, 0.0, 10.0], [1, 5.0, 0.0, 11.0], [1, 5.0, 0.0, 12.0], [1, 5.0, 0.0, 13.0], [1, 5.0, 0.0, 14.0], [1, 5.0, 0.0, 15.0], [1, 5.0, 0.0, 16.0], [1, 5.0, 0.0, 17.0], [1, 5.0, 0.0, 18.0], [1, 5.0, 0.0, 19.0], [1, 5.0, 0.0, 20.0], [1, 4.975, 0.4993746088859547, -20.0], [1, 4.975, 0.4993746088859547, -19.0], [1, 4.975, 0.4993746088859547, -18.0], [1, 4.975, 0.4993746

In [12]:
s = np.array(ans)

In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame(s)

In [15]:
df

0     1     2     3
0      1.0   5.0   0.0 -20.0
1      1.0   5.0   0.0 -19.0
2      1.0   5.0   0.0 -18.0
3      1.0   5.0   0.0 -17.0
4      1.0   5.0   0.0 -16.0
...    ...   ...   ...   ...
10593  1.0  50.0  18.0  20.0
10594  1.0  50.0  19.0 -20.0
10595  1.0  50.0  19.0  20.0
10596  1.0  50.0  20.0 -20.0
10597  1.0  50.0  20.0  20.0

[10598 rows x 4 columns]

In [16]:
df.to_csv('pore.csv')

In [17]:
print(s)

[[  1.   5.   0. -20.]
 [  1.   5.   0. -19.]
 [  1.   5.   0. -18.]
 ...
 [  1.  50.  19.  20.]
 [  1.  50.  20. -20.]
 [  1.  50.  20.  20.]]


In [18]:
n = s.shape[0]

In [19]:
f = open('data.txt', 'w')

In [20]:
f.write('length - ' +str(l)+', depth- ' +str(d)+', width- '+str(w)+', dia- '+str(dh)+', dia big- '+str(db)+', dia small - '+str(ds)+'\n\n')

84

In [21]:
f.write(str(n+num)+' atoms\n' + str(num-1) + ' bonds\n\n')

21

In [238]:
f.write('2 atom types\n1 bond types\n\n')

27

In [239]:
f.write(str(-l/2-0.5)+' '+str(l/2+0.5)+' xlo xhi\n'+str(-d/2-0.5)+' '+str(d/2+0.5)+' ylo yhi\n' + str(-w/2-140)+' '+str(w/2+140)+' zlo zhi\n\n')

60

In [240]:
f.write('Atoms\n\n')

7

In [241]:
for i in range(s.shape[0]):
    f.write(str(i+1)+' 1 1 0 '+str(s[i,1])+' '+str(s[i,2])+' '+str(s[i,3])+'\n')

In [242]:
for i in range(num):
    f.write(str((s.shape[0]+i+1))+' 2 2 -1 0 0 '+str(-w/2+(-i)+1)+'\n')
f.write('\n')

1

In [243]:
f.write('Masses\n\n')

8

In [244]:
f.write('1 1\n2 1\n\n')

9

In [245]:
f.write('Bonds\n\n')
for i in range(num-1):
    f.write(str(i+1) + ' 1 '+ str((s.shape[0]+i+1)) + ' ' + str((s.shape[0]+i+2))+'\n')
f.write('\n')

1

In [246]:
f.close()